import { Helmet } from 'react-helmet-async';
import { Link } from 'react-router-dom';
import { ArrowRight } from 'lucide-react';

const pageStyle = { background: 'var(--color-cream)', minHeight: '80vh', padding: '60px 20px' };
const containerStyle = { maxWidth: '860px', margin: '0 auto' };
const headingStyle = { fontFamily: 'var(--font-heading)', color: 'var(--color-primary)', fontSize: 'clamp(2rem, 5vw, 3rem)', textAlign: 'center', marginBottom: '16px' };
const subStyle = { color: 'var(--color-text-muted)', textAlign: 'center', marginBottom: '48px', fontStyle: 'italic' };
const cardStyle = { background: 'white', borderRadius: '20px', padding: '40px', boxShadow: 'var(--shadow-card)', lineHeight: 1.8, color: 'var(--color-text)', fontSize: '0.95rem' };

export function About() {
  return (<><Helmet><title>About Us – Shree Vastra</title></Helmet><div style={pageStyle}><div style={containerStyle}><h1 style={headingStyle}>Our Story</h1><p style={subStyle}>Born from a love of Indian craftsmanship and women's elegance</p><div style={cardStyle}><p>Shree Vastra was founded with one dream — to make every woman feel beautiful in her own heritage. We curate the finest ethnic wear from skilled artisans across India, bringing timeless designs to your doorstep.</p><br /><p><strong>Our Mission:</strong> To make premium ethnic fashion accessible, sustainable, and joyful for every Indian woman.</p><br /><p><strong>Our Vision:</strong> A world where every woman celebrates her culture with pride and elegance.</p></div></div></div></>);
}

export function Contact() {
  return (<><Helmet><title>Contact Us – Shree Vastra</title></Helmet><div style={pageStyle}><div style={containerStyle}><h1 style={headingStyle}>Get in Touch</h1><p style={subStyle}>We're here to help, always</p><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '28px' }}><div style={cardStyle}><h2 style={{ fontFamily: 'var(--font-heading)', color: 'var(--color-primary)', marginBottom: '20px' }}>Contact Info</h2>          <p>📞 +91 97231 40922</p>
            <p>✉️ support.shreevastra@gmail.com</p>
            <p>📍 Rajkot, Gujarat, India</p>
            <p style={{ marginTop: '16px' }}><a href="https://wa.me/919723140922" style={{ color: 'var(--color-accent)', fontWeight: 600 }}>💬 Chat on WhatsApp</a></p></div><div style={cardStyle}><h2 style={{ fontFamily: 'var(--font-heading)', color: 'var(--color-primary)', marginBottom: '20px' }}>Send a Message</h2><form style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>{['Your Name', 'Email Address', 'Subject'].map(p => (<input key={p} placeholder={p} style={{ padding: '10px 14px', borderRadius: '8px', border: '1px solid var(--color-border)', fontFamily: 'var(--font-body)', outline: 'none' }} />))}<textarea placeholder="Your Message" rows={4} style={{ padding: '10px 14px', borderRadius: '8px', border: '1px solid var(--color-border)', fontFamily: 'var(--font-body)', outline: 'none', resize: 'vertical' }} /><button className="btn-primary">Send Message</button></form></div></div></div></div></>);
}

export function FAQ() {
  const faqs = [['What is the return policy?', '7-day easy returns on all orders. Items must be unused and in original packaging.'], ['How long does delivery take?', 'Standard: 4-7 days. Express: 2-3 days. COD available nationwide.'], ['Do you accept COD?', 'Yes! Cash on Delivery is available across all pin codes in India.'], ['How can I track my order?', 'Use the Track Order page with your order ID, or check your email for updates.'], ['Can I exchange for a different size?', 'Yes, size exchanges are free within 7 days of delivery.']];
  return (<><Helmet><title>FAQs – Shree Vastra</title></Helmet><div style={pageStyle}><div style={containerStyle}><h1 style={headingStyle}>Frequently Asked Questions</h1><p style={subStyle}>Everything you need to know</p><div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>{faqs.map(([q, a]) => (<div key={q} style={cardStyle}><h3 style={{ color: 'var(--color-primary)', fontFamily: 'var(--font-heading)', marginBottom: '8px' }}>{q}</h3><p>{a}</p></div>))}</div></div></div></>);
}

export function SizeGuide() {
  return (<><Helmet><title>Size Guide – Shree Vastra</title></Helmet><div style={pageStyle}><div style={containerStyle}><h1 style={headingStyle}>Size Guide</h1><p style={subStyle}>Find your perfect fit</p><div style={cardStyle}><table style={{ width: '100%', borderCollapse: 'collapse' }}><thead><tr style={{ background: 'var(--color-cream)' }}>{['Size', 'Bust (inches)', 'Waist (inches)', 'Hip (inches)'].map(h => <th key={h} style={{ padding: '12px', textAlign: 'left', borderBottom: '2px solid var(--color-border)', color: 'var(--color-primary)' }}>{h}</th>)}</tr></thead><tbody>{[['XS', '32', '26', '36'], ['S', '34', '28', '38'], ['M', '36', '30', '40'], ['L', '38', '32', '42'], ['XL', '40', '34', '44'], ['XXL', '42', '36', '46']].map(([s, ...m]) => (<tr key={s}><td style={{ padding: '10px 12px', borderBottom: '1px solid var(--color-border)', fontWeight: 700, color: 'var(--color-primary)' }}>{s}</td>{m.map((v, i) => <td key={i} style={{ padding: '10px 12px', borderBottom: '1px solid var(--color-border)' }}>{v}"</td>)}</tr>))}</tbody></table></div></div></div></>);
}

const policyPage = (title, content) => () => (<><Helmet><title>{title} – Shree Vastra</title></Helmet><div style={pageStyle}><div style={containerStyle}><h1 style={headingStyle}>{title}</h1><div style={cardStyle} dangerouslySetInnerHTML={{ __html: content }} /></div></div></>);

export const PrivacyPolicy = policyPage('Privacy Policy', '<p>Your privacy is important to us. We collect only necessary data to process your orders and improve your experience. We never sell your personal information to third parties. All data is encrypted and stored securely.</p><br/><p>Last updated: May 2024</p>');
export const ShippingPolicy = policyPage('Shipping Policy', '<p><strong>Free Shipping</strong> on all orders above ₹999.</p><br/><p>Standard delivery: ₹99 — 4-7 business days<br/>Express delivery: ₹199 — 2-3 business days</p><br/><p>We ship across all pin codes in India via Shiprocket, Delhivery, and Blue Dart.</p>');
export const ReturnPolicy = policyPage('Return & Refund Policy', '<p>We offer a <strong>7-day return policy</strong> on all products. Items must be unused, unwashed, and in original packaging with tags intact.</p><br/><p>Refunds are processed within 5-7 business days to your original payment method.</p>');
export const TermsConditions = policyPage('Terms & Conditions', '<p>By using Shree Vastra, you agree to our terms of service. All prices are inclusive of GST. We reserve the right to cancel orders in case of pricing errors or stock unavailability.</p>');
export const ForgotPassword = () => (<><Helmet><title>Forgot Password – Shree Vastra</title></Helmet><div style={{ minHeight: '60vh', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '40px' }}><div style={{ background: 'white', borderRadius: '24px', padding: '48px', width: '100%', maxWidth: '400px', boxShadow: 'var(--shadow-card)', textAlign: 'center' }}><h1 style={{ fontFamily: 'var(--font-heading)', color: 'var(--color-primary)', marginBottom: '12px' }}>Reset Password</h1><p style={{ color: 'var(--color-text-muted)', marginBottom: '28px' }}>Enter your email to receive a reset OTP</p><input type="email" placeholder="your@email.com" style={{ width: '100%', padding: '12px 16px', borderRadius: '10px', border: '1.5px solid var(--color-border)', fontSize: '0.9rem', fontFamily: 'var(--font-body)', outline: 'none', marginBottom: '16px', boxSizing: 'border-box' }} /><button className="btn-primary" style={{ width: '100%', justifyContent: 'center' }}>Send OTP</button><p style={{ marginTop: '20px', fontSize: '0.875rem' }}><Link to="/login" style={{ color: 'var(--color-accent)', textDecoration: 'none' }}>← Back to Login</Link></p></div></div></>);
export const SearchResults = () => { const [q] = [new URLSearchParams(window.location.search).get('q')]; return <div style={{ padding: '40px', textAlign: 'center' }}><h2 style={{ fontFamily: 'var(--font-heading)', color: 'var(--color-primary)' }}>Search Results for "{q}"</h2><p style={{ color: 'var(--color-text-muted)', marginTop: '8px' }}>Browse products below</p><div style={{ marginTop: '32px' }}><Link to="/shop" className="btn-primary" style={{ textDecoration: 'none' }}>View All Products</Link></div></div>; };
export const Blog = () => (<><Helmet><title>Blog – Shree Vastra</title></Helmet><div style={pageStyle}><div style={containerStyle}><h1 style={headingStyle}>Fashion Blog</h1><p style={subStyle}>Style tips, trends & stories from Shree Vastra</p><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', gap: '24px' }}>{['5 Ways to Style Your Saree for Office', 'Festive Kurti Trends 2024', 'How to Choose the Right Fabric'].map(title => (<div key={title} style={{ ...cardStyle, padding: '24px' }}><div style={{ height: '160px', background: 'linear-gradient(135deg, var(--color-primary), var(--color-accent))', borderRadius: '12px', marginBottom: '16px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '2rem' }}>✍️</div><h3 style={{ fontFamily: 'var(--font-heading)', color: 'var(--color-primary)', marginBottom: '8px' }}>{title}</h3><p style={{ color: 'var(--color-text-muted)', fontSize: '0.875rem' }}>Fashion tips & trends from our style experts.</p><Link to="/blog/demo" style={{ color: 'var(--color-accent)', textDecoration: 'none', fontWeight: 600, fontSize: '0.875rem', display: 'inline-flex', alignItems: 'center', gap: '4px', marginTop: '12px' }}>Read More <ArrowRight size={14} /></Link></div>))}</div></div></div></>);
export const BlogPost = () => (<div style={{ ...pageStyle, ...containerStyle }}><h1 style={{ fontFamily: 'var(--font-heading)', color: 'var(--color-primary)', fontSize: '2rem' }}>Blog Post Coming Soon</h1></div>);
